### ISSUE TITLE
Sprites issue

### ISSUE THREAD

**Issue by RandomsitoXD** [Cloudydude/ES_Amy#1]
So when im playing, first of all, Robotnik appears as pure numbers, the springs are with Tails sprites, the spikes are numbers, double Amy on Special stages, wrong sprite on spindash, dissapearing sprites. If there's a tutorial, please send.

**Comment by Cloudydude** [comment]
What you're experiencing is a mod conflict and is not coming from ES Amy. Please re-arrage your mod order, or remove some mods to find the issue.

**Comment by RandomsitoXD** [comment]
I forgot to tell that I saw videos that they are combining with the mod Extra Save Slot and many of the ES mods are getting conflict, while in other videos not. Is there any answer to that?
Because when I enable the mods, the sprites are ruined, when I disable it, the mods are fine

**Comment by Cloudydude** [comment]
Like I said, there's probalby another mod causing the issue. I don't know what mods your using, but you'll have to see which one is causing the issue.
